version: "3.9"

services: 
    mariadb:
        image: 192.168.201.120:5000/appdb
        build: ./db/
        networks:
            - local_net
        environment: 
            - MARIADB_ROOT_PASSWORD=Pa55W0rd
            - MYSQL_DATABASE=somedatabase
            - MYSQL_USER=someuser
            - MYSQL_PASSWORD=somepassword

    pyweb:
        image: 192.168.201.120:5000/appweb
        build: ./web/
        restart: always
        deploy:
            replicas: 3
        ports:
            - 9000:3000
        networks:
            - local_net
        depends_on: 
            - mariadb

networks: 
    local_net:
